### ISSUE TITLE
Link to resources is dead

### ISSUE THREAD

**Issue by neumannm** [opener-project/ner-base#3]
The links to nerc-default-resources.tgz and nerc-resources.tgz are both dead.

**Comment by ragerri** [comment]
Hi Mandy,

Those links should not be there, sorry about that. If you are planning to
try custom models using the core of the ner-base component you can simply
go here

https://github.com/ixa-ehu/ixa-pipe-nerc

Best,

R

**Comment by neumannm** [comment]
Thank you. I think I don't quite get the connection between the OpeNER project and the IXA Pipe Project.

**Comment by ragerri** [comment]
ixa-pipe-nerc is the core of the ner-base component of OpeNER, see http://www.opener-project.eu/getting-started/architecture-overview.html

**Comment by neumannm** [comment]
Thank you for your clarification and the link.
