### ISSUE TITLE
training model

### ISSUE THREAD

**Issue by angelo337** [opener-project/ner-base#4]
hi there
I am working on a project and I would like to include more locations and entities recognition on the code, could someone please point me out some resources? in order to train the model and test it.
thanks

**Comment by ragerri** [comment]
Hello, AFAIK you need to use the core directly to train new models. You can read the documentation in the core site. https://github.com/ixa-ehu/ixa-pipe-nerc#training

**Comment by YorickPeterse** [comment]
Correct, the Ruby code (and the corresponding executable) doesn't support the training mode, so you'll have to use the Java code correctly.
